//Problem: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

//Solution: 

function fibonacciEvenSum(n) {
  
  let fiboArray = [1, 2];
  let fiboSum = 0;

  // Generate Fibonacci sequence up to n
  for (let i = 2; ; i++) {
    let nextFiboNumber = fiboArray[i - 1] + fiboArray[i - 2];
    if (nextFiboNumber > n) {
      break;
    }
    fiboArray.push(nextFiboNumber);
  }

  // Sum the even fibonacci numbers
  for (let i = 0; i < fiboArray.length; i++) {
    if (fiboArray[i] % 2 === 0) {
      fiboSum += fiboArray[i];
    }
  }

  return fiboSum;
}
